"""Add LlmUsage table

Revision ID: a0f1a702900c
Revises: 1da50af1ca5a
Create Date: 2026-05-28 18:38:31.668149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f1a702900c'
down_revision: Union[str, Sequence[str], None] = '1da50af1ca5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_conversation_id'), 'llm_usage', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_id'), 'llm_usage', ['id'], unique=False)
    op.create_index(op.f('ix_llm_usage_message_id'), 'llm_usage', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_usage_message_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_conversation_id'), table_name='llm_usage')
    op.drop_table('llm_usage')
    # ### end Alembic commands ###
